### ISSUE TITLE
Использование метода model_dump

### ISSUE THREAD

**Issue by Eytes** [Eytes/BookingBot#4]
https://github.com/Eytes/BookingBot/blob/d634cd22103abadbcd9beefe8a80ec799aaaa409/src/backend/repositories/user.py#L9C1-L23C10

```python
@classmethod
async def create(cls, user: CreateUserSchema) -> ItemId:
    """Создает новую запись о пользователе в базе данных."""
    return await user_collection.insert_one(user.model_dump())
```

**Comment by Furlos** [comment]
Я сделал [комит](https://github.com/Eytes/BookingBot/commit/a953bf421ff228ac4c6a5e1fc15b999fda3e4a6e) с сделаным заданием. Прошу проверить.

**Comment by Eytes** [comment]
На model_dump замены была произведена. Однако у тебя не совпадает в сигнатуре функции тип возвращаемого значения с тем, что у тебя написано в return
