### ISSUE TITLE
Фабрика для коллекций

### ISSUE THREAD

**Issue by Eytes** [Eytes/BookingBot#6]
https://github.com/Eytes/BookingBot/blob/d634cd22103abadbcd9beefe8a80ec799aaaa409/src/backend/repositories/__init__.py#L7C1-L9C42

Советую написать фабрику для создания коллекций в  Mongo и автоматического создания registry для работы с этой коллекцией. Советую посетить сайт `refactoring guru`

Например: 
```python
class MongoRepositoryFactory:
    def __init__(self, database: AsyncIOMotorDatabase):
        self.__database = database

    def create_collection_and_get_repository[MongoRepository](
         self, 
         repository: Type[MongoRepository],
    ) -> MongoRepository:
        """Автоматически создается коллекция и набор CRUD операций для этой коллекции"""
        collection_name = ...
        return repository(self.__database[collection_name])
```

**Comment by Furlos** [comment]
[Финальный комит](https://github.com/Eytes/BookingBot/commit/e7d6d83ed42599986ed0f7e8f67d9ab6adbdbdb0)
