### ISSUE TITLE
Тип данных для валидации номера телефона из библиотеки pydantic

### ISSUE THREAD

**Issue by Eytes** [Eytes/BookingBot#7]
https://github.com/Eytes/BookingBot/blob/d634cd22103abadbcd9beefe8a80ec799aaaa409/src/backend/base_types.py#L7C1-L7C25

https://docs.pydantic.dev/latest/api/pydantic_extra_types_phone_numbers/

**Comment by Furlos** [comment]
https://github.com/Eytes/BookingBot/commit/7155a2c33c829c5a0bf4ee01d4f6983e2c842b61 закрываю)

**Comment by Eytes** [comment]
Зачем создавать свой тип данный, который полностью дублирует тип номера телефона из библиотеки?

Почему бы не указать аннотацию типа прямо в схеме данных?

**Comment by Furlos** [comment]
[комит](https://github.com/Eytes/BookingBot/blob/312cb2a3cb7743d0b3c8fee8a253b1aa22c3ee90/src/backend/schemas/user.py)
